-- import Data.List
-- import Data.Char
-- import System.Random
import Test.QuickCheck


-- class Arbitrary a where
--     arbitrary :: Gen a


-- generate :: Gen a -> IO a


property1 :: Integer -> Bool
property1 n = fact n == n * fact (n - 1)

property2 :: Integer -> Bool
property2 = even

fact :: Integer -> Integer
fact n = if n == 0 then 1 else n * fact (n-1)


main :: IO ()
main = do
    arbitrary_no <- generate arbitrary :: IO Integer
    print $ "Arbitrary number generated by Gen: " ++ show arbitrary_no
    print $ fact arbitrary_no



{-
--------- LIBRARIES ---------

We utilized the QuickCheck library for random number generation.

--------- CODE DESCRIPTION (PURPOSE, FEATURES, ARCHITECTURE) ---------

The purpose of this exercise is finding a haskel

--------- TESTING APPROACH ---------

"Arbitrary number generated by Gen: 10"
3628800

"Arbitrary number generated by Gen: 25"
15511210043330985984000000

-}



